# Abilita il supporto ad AndroidX (necessario per le librerie recenti)
android.useAndroidX=true

# Converte automaticamente le librerie legacy per renderle compatibili con AndroidX
android.enableJetifier=true

# Ottimizzazione memoria e prestazioni per il build daemon su GitHub Actions
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
